name: snel

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@004814556e37c54a2f6e31384c9e18e983317366
        with:
          deno-version: v1.x

      - name: Setup snel
        run: deno run --allow-run --allow-read https://deno.land/x/snel/install.ts

      - name: Run build
        working-directory: ./example
        run: snel build
